#!/bin/sh
path=$(pwd)


ln -sf "$path"/sway-run /usr/local/bin/sway-run
ln -sf "$path"/wayland_enablement.sh /usr/local/bin/wayland_enablement.sh

# Home directory
ln -sf "$path"/.bash_profile "$HOME"/.bash_profile
ln -sf "$path"/.bashrc "$HOME"/.bashr
ln -sf "$path"/.gitconfig "$HOME"/.gitconfig
ln -sf "$path"/.ideavimrc "$HOME"/.ideavimrc
ln -sf "$path"/.vimrc "$HOME"/.vimrc
ln -sf "$path"/.zshrc "$HOME"/.zshrc

# Config directory
[ ! -d "$HOME"/.config ] && mkdir "$HOME"/.config

[ -d "$HOME"/.config/bumblebee-status ] && rm -rf "$HOME"/.config/bumblebee-status
ln -sf "$path"/config/bumblebee-status/ "$HOME"/.config/bumblebee-status

[ -d "$HOME"/.config/dunst ] && rm -rf "$HOME"/.config/dunst
ln -sf "$path"/config/dunst/ "$HOME"/.config/dunst

[ -d "$HOME"/.config/fontconfig ] && rm -rf "$HOME"/.config/fontconfig
ln -sf "$path"/config/fontconfig/ "$HOME"/.config/fontconfig

[ -d "$HOME"/.config/i3 ] && rm -rf "$HOME"/.config/i3
ln -sf "$path"/config/i3/ "$HOME"/.config/i3

[ -d "$HOME"/.config/gtk-3.0 ] && rm -rf "$HOME"/.config/gtk-3.0
ln -sf "$path"/config/gtk-3.0/ "$HOME"/.config/gtk-3.0

[ -d "$HOME"/.config/kitty ] && rm -rf "$HOME"/.config/kitty
ln -sf "$path"/config/kitty/ "$HOME"/.config/kitty

[ -d "$HOME"/.config/networkmanager-dmenu ] && rm -rf "$HOME"/.config/networkmanager-dmenu
ln -sf "$path"/config/networkmanager-dmenu/ "$HOME"/.config/networkmanager-dmenu

[ -d "$HOME"/.config/picom ] && rm -rf "$HOME"/.config/picom
ln -sf "$path"/config/picom/ "$HOME"/.config/picom

[ -d "$HOME"/.config/polybar ] && rm -rf "$HOME"/.config/polybar
ln -sf "$path"/config/polybar/ "$HOME"/.config/polybar

[ -d "$HOME"/.config/ranger ] && rm -rf "$HOME"/.config/ranger
ln -sf "$path"/config/ranger/ "$HOME"/.config/ranger

[ -d "$HOME"/.config/rofi ] && rm -rf "$HOME"/.config/rofi
ln -sf "$path"/config/rofi/ "$HOME"/.config/rofi

[ -d "$HOME"/.config/sway ] && rm -rf "$HOME"/.config/sway
ln -sf "$path"/config/sway/ "$HOME"/.config/sway
chmod -R +x "$HOME"/.config/sway/scripts/

[ -d "$HOME"/.config/swaync ] && rm -rf "$HOME"/.config/swaync
ln -sf "$path"/config/swaync/ "$HOME"/.config/swaync

[ -d "$HOME"/.config/swaylock ] && rm -rf "$HOME"/.config/swaylock
ln -sf "$path"/config/swaylock/ "$HOME"/.config/swaylock

[ -d "$HOME"/.config/waybar ] && rm -rf "$HOME"/.config/waybar
ln -sf "$path"/config/waybar/ "$HOME"/.config/waybar
chmod -R +x "$HOME"/.config/waybar/modules/

[ -d "$HOME"/.config/wofi ] && rm -rf "$HOME"/.config/wofi
ln -sf "$path"/config/wofi/ "$HOME"/.config/wofi

[ -d "$HOME"/.config/zathura ] && rm -rf "$HOME"/.config/zathura
ln -sf "$path"/config/zathura/ "$HOME"/.config/zathura

ln -sf "$path"/config/.gtkrc-2.0 "$HOME"/.config/.gtkrc-2.0
ln -sf "$path"/config/pavucontrol.ini "$HOME"/.config/pavucontrol.ini
ln -sf "$path"/config/user-dirs.dirs "$HOME"/.config/user-dirs.dirs

# Local directory
[ ! -d "$HOME"/.local ] && mkdir -p "$HOME"/.local/share
[ ! -d "$HOME"/.local/share ] && mkdir "$HOME"/.local/share
[ -d "$HOME"/.local/share/fonts ] && rm -r "$HOME"/.local/share/fonts
ln -sf "$path"/local/share/fonts "$HOME"/.local/share/fonts
[ -d "$HOME"/.local/share/icons ] && rm -r "$HOME"/.local/share/icons
ln -sf "$path"/local/share/icons "$HOME"/.local/share/icons
[ -d "$HOME"/.local/share/rofi ] && rm -r "$HOME"/.local/share/rofi
ln -sf "$path"/local/share/rofi "$HOME"/.local/share/rofi
[ -d "$HOME"/.local/share/themes ] && rm -r "$HOME"/.local/share/themes
ln -sf "$path"/local/share/themes "$HOME"/.local/share/themes

[ -d "$HOME"/.local/share/wallpapers ] && rm -r "$HOME"/.local/share/wallpapers
ln -sf "$path"/local/share/wallpapers "$HOME"/.local/share/wallpapers

# Set executable
chmod +x $HOME/.config/polybar/launch.sh
