format = """
$os$username[@](bg:#5e81ac fg:#2e3440)$hostname\
[](bg:#81a1c1 fg:#5e81ac)\
$directory\
$git_branch$git_status\
$php\
$cmd_duration\
$time\
[](fg:prev_bg)\
$line_break\
$character
"""

# GIT
# ===

[git_branch]
format = '[](bg:#88c0d0 fg:prev_bg)[ $symbol$branch(:$remote_branch) ](fg:#2e3440 bg:#88c0d0)'
symbol = " "

[git_status]
format = '[($all_status$ahead_behind )](fg:#bf616a bg:#88c0d0)'

# LANGUAGES
# =========

[php]
symbol = " "
format = '[](bg:#8fbcbb fg:prev_bg)[ $symbol($version) ](fg:#2e3440 bg:#8fbcbb)'

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#5e81ac"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

[os.symbols]
Macos = "  "

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[directory]
style = "fg:#2e3440 bg:#81a1c1"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"

[sudo]
disabled = false
symbol = " "
style = "fg:#2e3440 bg:#d9dee9"
format = "[ $symbol]($style)"

[cmd_duration]
format = '[](bg:#d9dee9 fg:prev_bg)[ 󰔚 $duration ](fg:#2e3440 bg:#d9dee9)'


[time]
disabled = false
time_format = "%R"
format = '[](bg:#b48ead fg:prev_bg)[  $time ](fg:#2e3440 bg:#b48ead)'

[character]
success_symbol = "[ 󷞩](bold green)"
error_symbol = "[ 󷞩](bold red)"
vimcmd_symbol = "[  󷞩](bold green)"
