### Variables
#
# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Escape key bindings.
set $Escape Caps_Lock

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Your preferred terminal emulator
set $term kitty
set $term_float kitty --class="termfloat"

# Your preferred application launcher
# set $menu dmenu_path | wofi --show drun -I | xargs swaymsg exec --
set $menu wofi --show drun --allow-images --allow-markup --hide-scroll --no-actions -lines 10 -width 35 | xargs swaymsg exec --

# Add --to-code to bindsym, support for non-latin layouts
set $bindsym bindsym --to-code

# Brightness control
set $brightness_step bash -c 'echo $(( $(light -Mr) / 100 * 5 < 1 ? 1 : $(( $(light -Mr) / 100 * 5 )) ))'
set $brightness_up light -r -A $($brightness_step) && $onscreen_bar $(light -G | cut -d'.' -f1)
set $brightness_down light -r -U $($brightness_step) && $onscreen_bar $(light -G | cut -d'.' -f1)

# Volume control
set $volume_down pactl set-sink-volume @DEFAULT_SINK@ -5% && $onscreen_bar $(pamixer --get-volume)
set $volume_up pactl set-sink-volume @DEFAULT_SINK@ +5% && $onscreen_bar $(pamixer --get-volume)
set $volume_mute pactl set-sink-mute @DEFAULT_SINK@ toggle && $(pamixer --get-volume)

# Clipboard history
set $clipboard cliphist list | wofi -dmenu -p "Select item to copy" -lines 10 -width 35 -theme-str $wofi_theme | cliphist decode | wl-copy
set $clipboard-del cliphist list | wofi -dmenu -p "Select item to delete" -lines 10 -width 35 -theme-str $wofi_theme | cliphist delete

### Idle configuration
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
#
set $idle_timeout 240
set $locking_timeout 300
set $screen_timeout 600

# Workspaces
set $ws1   "1:web"
set $ws2   "2:code"
set $ws3   "3:chat"
set $ws4   "4:term"
set $ws5   "5:apps"
set $ws6   "6:music"
set $ws7   "7:others"
set $ws8   "8:others"
set $ws9   "9:others"
set $ws_default   "24:desktop"
