# i3-gaps
smart_borders on      # borders only if more than one container in the workspace
smart_gaps on         # gaps only if more than one container in the workspace
gaps inner 10         # global gap size

# Pixel borders remove title bars completely because of compton shadows
for_window [class="^.*"] border pixel 5

#
# Default workspaces for common programs:
#
assign [class="^Firefox$"] $ws1
assign [class="Slack"] $ws3
assign [class="TelegramDesktop"] $ws3
assign [class="ticktick"] $ws5
assign [class="betterbird"] $ws5
for_window [class="Spotify"] move to workspace $ws6

#
# Floating mode for specific applications:
#
for_window [id="termfloat"] floating enable
for_window [class="Galculator"] floating enable
for_window [id="pavucontrol-qt"] floating enable
for_window [id="udiskie"] floating enable
for_window [class="1Password"] floating enable
# for_window [title="Morgen Calendar"] floating enable
for_window [id="galculator"] floating enable
for_window [title="Application Finder"] floating enable
# generated windows. (https://www.reddit.com/r/swaywm/comments/uwdboi/how_to_make_chrome_popup_windows_floating/)
for_window [title="(?:Open|Save) (?:File|Folder|As)"] floating enable
for_window [title="(?:Open|Save) (?:File|Folder|As)"] resize set 800 600
for_window [window_role="Preferences"] floating enable
