# https://www.fosskers.ca/en/blog/wayland
# PolicyKit agent
exec_always /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Notification daemon
exec /usr/lib/xfce4/notifyd/xfce4-notifyd &

exec_always --no-startup-id dunst -config ~/.config/dunst/dunstrc

exec_always ~/.config/sway/scripts/import-gsettings.sh
exec_always spice-vdagent

exec picom -b &
exec udiskie -a -n &
exec blueman-applet &
exec slack &
exec firefox &
exec com.ticktick.TickTick &
exec betterbird &
exec spotify &
exec telegram-desktop &
exec /opt/Morgen/morgen --hidden &
