import 01-default.conf;
import 70-colors.conf;
# import gaps.conf;
import 80-output.conf;
import 85-input.conf;
import 96-bar.conf;
import 98-applications-defaults.conf;
import 99-autostart-applications.conf;
