# Add your additional Hyprland configurations here

# -----------------------------------------------------
# Keyboard Layout
# overrides: ~/.config/hypr/conf/keyboard.conf
# -----------------------------------------------------
input {
    kb_layout = us,ru
    kb_options = caps:swapescape,grp:alt_shift_toggle
}

# -----------------------------------------------------
# Autostart (additions)
# see also: ~/.config/hypr/conf/autostart.conf
# -----------------------------------------------------
exec-once = hyprshade on blue-light-filter-50
