# https://www.fosskers.ca/en/blog/wayland
# PolicyKit agent
exec_always /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Notification daemon
exec swaync

exec swayidle -w \
    timeout $idle_timeout 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout $locking_timeout "bash ~/.config/swaylock/lock.sh" \
    timeout $screen_timeout 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'playerctl pause' \
    before-sleep "bash ~/.config/swaylock/lock.sh" & \
    lock "bash ~/.config/swaylock/lock.sh" &

exec {
    '[ -x "$(command -v udiskie)" ] && udiskie'
    '[ -x "$(command -v blueman-applet)" ] && blueman-applet'
    '[ -x "$(command -v slack)" ] && slack'
    '[ -x "$(command -v firefox)" ] && firefox'
    '[ -x "$(command -v com.ticktick.TickTick)" ] && com.ticktick.TickTick'
    '[ -x "$(command -v com.ulduzsoft.Birdtray)" ] && com.ulduzsoft.Birdtray'
    '[ -x "$(command -v spotify)" ] && spotify'
    '[ -x "$(command -v telegram-desktop)" ] && telegram-desktop'
    '[ -x "$(command -v autotiling)" ] && autotiling -w 3 4'
    '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch cliphist store'
    '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch pkill -RTMIN+9 waybar'
}
exec_always {
    '~/.config/sway/scripts/import-gsettings.sh'
    '[ -x "$(command -v spice-vdagent)" ] && spice-vdagent'
    '[ -x "$(command -v nwg-drawer)" ] && nwg-drawer -r'
}
